version: "3.8"

services:
  admin_frontend:
    container_name: admin_frontend
    build: .
    ports:
      - "3001:3000"
    restart: always
    environment:
      NODE_ENV: production
      NUXT_LOG_LEVEL: error
      HOST: 0.0.0.0   # чтобы Nuxt слушал все интерфейсы
      PORT: 3000      # порт внутри контейнера
      NUXT_LOG_LEVEL: error