version: "3.8"

services:
  admin_frontend:
    container_name: kenya_coffee_admin
    build: .
    ports:
      - "3001:3000"
    restart: always
    environment:
      NODE_ENV: production
      NUXT_LOG_LEVEL: error
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      BACKEND_ADDRESS: https://kenya-coffee.ru/backend
      WS_ADDRESS: wss://kenya-coffee.ru/backend